### ISSUE TITLE
groupdocscloud/viewer-sdk-php 18.2 requires aspose/storage-sdk-php 1.0.*

### ISSUE THREAD

**Issue by yoges89** [groupdocs-viewer-cloud/groupdocs-viewer-cloud-php#1]
I am trying to install it using composer but somehow it is giving an error
Problem 1
    - Installation request for groupdocscloud/viewer-sdk-php ^18.2 -> satisfiable by groupdocscloud/viewer-sdk-php[18.2].
    - groupdocscloud/viewer-sdk-php 18.2 requires aspose/storage-sdk-php 1.0.* -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

**Comment by vladimir-litvinchik** [comment]
Hi Yogesh, 
The issue was fixed, please try installing it one more time.
Also, check that your dependency registered as `groupdocscloud/viewer-sdk-php": "*"` or require latest version explicitly `groupdocscloud/viewer-sdk-php": "18.2.1"`. 
Thanks
